[package]
name = "mlsub"
description = "Template."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/mlsub"
documentation = "https://docs.rs/mlsub"
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
im = "12.3.0"
seahash = "~3"
itertools = "0.8.0"

[dev-dependencies]
iter-set = "0.2.0"
proptest = "0.8.7"
lazy_static = "1.2.0"
rand = "0.5.5"
